kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: reviews-service-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: reviews-v2
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
